global:
  security:
    allowInsecureImages: true

auth:
  username: forenshield
  password: Welabs2026!

image:
  repository: bitnamilegacy/rabbitmq

volumePermissions:
  image:
    repository: bitnamilegacy/os-shell

persistence:
  enabled: true
  size: 10Gi
  storageClass: gp3

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

nodeSelector:
  eks.amazonaws.com/nodegroup: backend-ng

service:
  type: ClusterIP
  ports:
    amqp: 5672

metrics:
  enabled: true

replicaCount: 1
