apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: forenshield
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80