apiVersion: v1
kind: Service
metadata:
  name: ai-fastapi
  namespace: forenshield
  labels:
    app: ai-fastapi
spec:
  type: ClusterIP
  selector:
    app: ai-fastapi
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP